version: "3.5"
services:
  waf:
    image: jpadron1986/ngwaf
    container_name: nginx
    networks:
      - nwaf
    ports:
      - "80:80"

    volumes:
      - ./app:/usr/share/nginx/html
  
  redis:
    image: redis
    container_name: bd
    ports:
      - "6379"

volumes:
  app:
networks:
  nwaf:
