version: "3.5"
services:
  waf:
    image: jpadron1986/ngwaf
    container_name: nginx
    networks:
      - nwaf
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./app:/usr/share/nginx/html
  redis:
    image: "redis:alpine"
    hostname: redis
    networks:
      - nwaf
    ports:
      - "6379:6379"
volumes:
  app:
networks:
  nwaf:
